package com.complex.event

import entity.Person

declare  Person
   @role(event)     // 要把插入的数据声明为event，默认是fact,
   @expires(20s)    // 用来显示设置事件的过期时间，也就是说过了这个时间，该事件就会从会话中移除，不能再使用
end


rule "testComplexEvent3"
    no-loop true
    when
        $eventA : Person()
        $eventB : Person( this after[ 0, 4m ] $eventA )
        over window:time(3s)
    then
        System.out.println("---ageA---"+$eventA.toString());
        System.out.println("---ageB---"+$eventB.toString());
end

