package com.rules

dialect "mvel"
import entity.Customer

rule "和了一瓶汽水"
    when
        $c:Customer(money>0,$m:money, $e:emptyBottle, $d :drinkBottleSum);
    then
        $c.money=$m-1;
        $c.emptyBottle=$e+1;
        $c.drinkBottleSum=$d+1;
        System.out.println($c.getName()+"有 "+$c.getMoney()+" 元， 有空瓶 "+$c.getEmptyBottle()+" 个， 喝了 "+$c.getDrinkBottleSum()+" 瓶。");
        update($c);
end

rule "用两个空瓶换了一瓶汽水"
    when
        $c:Customer(emptyBottle>1,$e:emptyBottle, $d:drinkBottleSum);
    then
        $c.emptyBottle=$e-2+1;
        $c.drinkBottleSum=$d+1;
         System.out.println($c.getName()+"有 "+$c.getMoney()+" 元， 有空瓶 "+$c.getEmptyBottle()+" 个(兑换了2个，又得到一个)， 喝了 "+$c.getDrinkBottleSum()+" 瓶。");
        update($c);
end

rule "结束"
    no-loop true
    when
         $c:Customer(money<=0,emptyBottle<2);
    then
         System.out.println("计算结束："+$c.getName()+"有 "+$c.getMoney()+" 元， 有空瓶 "+$c.getEmptyBottle()+" 个， 喝了 "+$c.getDrinkBottleSum()+" 瓶。");

end